spring:
  datasource:
      url: jdbc:mysql://localhost:3306/register_form?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

#for mail SMTP CONFIGURATION
  mail:
    host: smtp.gmail.com
    port: 587
    username: springcheck60@gmail.com
    password: wttq qxsh iykg wmva
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
